[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.2.1",
    "pyqt6-qt6>=6.9.1",
    "pyqt6>=6.9.1",
    "qtawesome>=1.4.0",
]
